dist: bionic
language: go
os: linux
jobs:
  include:
    - go: "1.13.x"
    - go: "1.13.x"
      osx_image: "xcode11.2"
      os: osx
    - go: "1.12.x"
install:
  - go get -t ./...
script: go test -v ./... -check.v
